on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflow/**'


jobs:
  build:
    name: Build the app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: pre-requisites Installation
        shell: powershell
        run: sudo apt install fortune-mod cowsay -y
      - name: run the script
        run: |
             ./wisecow.sh
             echo "ran script successfully"
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wisecow-artifact
        
      
        
        
