on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflow/**'

jobs:
  build:
    name: Build the app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Pre-requisites Installation
        run: |
          sudo apt update
          sudo apt install fortune-mod cowsay -y

      - name: Run the script
        run: |
          chmod +x wisecow.sh  # Ensure execute permission
          ./wisecow.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wisecow-artifact
          path: path/to/artifacts
